# -*- coding: utf-8 -*-
"""02_total_target_per_month.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SUW990u68qefd6gbWww-rrKGaZkGyEr
"""

import pandas as pd

# Carica il file CSV
df = pd.read_csv('02_input_target.csv')  # Sostituisci con il nome effettivo del tuo file

# Assicura che la colonna 'Quantity' sia numerica
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

# Raggruppa per mese e somma le quantità
somme_per_mese = df.groupby('Month')['Quantity'].sum()

# Stampa il risultato
print(somme_per_mese)

somme_per_mese.to_csv('somme_per_mese.csv')